#!/usr/bin/env node
/**
 * import.js — the one-shot Sheets -> D1 conversion. Node, no dependencies.
 *
 *   node migrate/import.js financetracker-export-*.json > seed.sql
 *   cd worker && npx wrangler d1 execute financetracker --remote --file=../seed.sql
 *
 * Input is what Export.gs wrote to Drive. Output on stdout is SQL; the RECONCILIATION
 * REPORT goes to stderr, so `> seed.sql` keeps them apart and you still see the report.
 *
 * The report is the blocking check of the whole migration: for every account it
 * recomputes the native balance from the ledger the way the app will
 * (starting + income - expense - transfers out + transfers in, inverted for
 * liabilities) and compares it against the sheet's own `Current Balance` formula
 * value. A single mismatch means the sign conventions or the transfer handling do not
 * agree, and the exit code is non-zero so a pipeline cannot ignore it.
 *
 * Conversions, all at this boundary and nowhere else:
 *   money/quantities -> integer micros, Math.round(x * 1e6)
 *   names            -> integer ids (accounts and categories, in sheet order)
 *   blank            -> NULL, never '' (a CHECK or a COALESCE would read '' as a value)
 *   Period           -> canonical 'yyyy-MMM', or NULL
 */
const fs = require('fs');

const M = 1e6;
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

const src = process.argv[2];
if (!src) { console.error('usage: node migrate/import.js <export.json> > seed.sql'); process.exit(2); }
const data = JSON.parse(fs.readFileSync(src, 'utf8'));
const sheet = (name) => (data.sheets && data.sheets[name] ? data.sheets[name].rows : []);

const problems = [];
const fail = (msg) => problems.push(msg);

// ── value helpers ────────────────────────────────────────────────────────────
const blank = (v) => v === '' || v === null || v === undefined;
/** A sheet cell as a number: strips thousands separators and (parenthesised) negatives. */
function num(v) {
  if (blank(v)) return 0;
  if (typeof v === 'number') return v;
  const s = String(v).replace(/,/g, '').replace(/^\((.*)\)$/, '-$1').trim();
  const n = parseFloat(s);
  return isNaN(n) ? 0 : n;
}
const toU = (v) => Math.round(num(v) * M);
const uOrNull = (v) => (blank(v) ? null : toU(v));
const numOrNull = (v) => (blank(v) ? null : num(v));
const txt = (v) => (blank(v) ? null : String(v).trim());

function isoDate(v, where) {
  if (blank(v)) return null;
  const s = String(v).trim();
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;
  const d = new Date(s);
  if (isNaN(d.getTime())) { fail(where + ': unparseable date ' + JSON.stringify(v)); return null; }
  return d.toISOString().slice(0, 10);
}

function periodKey(v, where) {
  if (blank(v)) return null;
  const m = /^(\d{4})-(\d{1,2}|[A-Za-z]{3,})$/.exec(String(v).trim());
  const i = m ? (/^\d+$/.test(m[2]) ? parseInt(m[2], 10) - 1
    : MONTHS.findIndex((n) => n.toLowerCase() === m[2].slice(0, 3).toLowerCase())) : -1;
  if (i < 0 || i > 11) { fail(where + ': unparseable Period ' + JSON.stringify(v)); return null; }
  return m[1] + '-' + MONTHS[i];
}

// ── SQL emit ─────────────────────────────────────────────────────────────────
const sql = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  return "'" + String(v).replace(/'/g, "''") + "'";
};
const out = [];
const say = (s) => out.push(s);
/** Multi-row INSERTs in chunks — one statement per 100 rows keeps the file executable. */
function insert(table, cols, rows) {
  for (let i = 0; i < rows.length; i += 100) {
    const chunk = rows.slice(i, i + 100);
    say('INSERT INTO ' + table + ' (' + cols.join(', ') + ') VALUES\n  ' +
      chunk.map((r) => '(' + cols.map((c) => sql(r[c])).join(', ') + ')').join(',\n  ') + ';');
  }
}

say('-- Generated by migrate/import.js from ' + src);
say('-- Source export: ' + (data.exportedAt || '(unknown)') + '  tz=' + (data.timeZone || '?'));
say('PRAGMA foreign_keys = OFF;');   // deletes below run child-first anyway; this survives a partial re-run
say('DELETE FROM ledger; DELETE FROM transactions; DELETE FROM budgets; DELETE FROM recurring;');
say('DELETE FROM categories; DELETE FROM accounts; DELETE FROM account_types;');
say('PRAGMA foreign_keys = ON;');
say('');

// ── account_types ────────────────────────────────────────────────────────────
const typeBySubtype = {};
const accountTypes = sheet('AccountType').filter((r) => r.Subtype).map((r) => {
  const type = /liab/i.test(String(r.Type)) ? 'Liability' : 'Asset';
  typeBySubtype[String(r.Subtype).trim()] = type;
  return { subtype: String(r.Subtype).trim(), type };
});
insert('account_types', ['subtype', 'type'], accountTypes);

// ── accounts ─────────────────────────────────────────────────────────────────
// A Shares account's ticker IS its name: the sheet's PHP formula reads
// GOOGLEFINANCE(A<row>), i.e. the name cell. (The only quoted GOOGLEFINANCE on the row is
// "CURRENCY:USDPHP", which is the FX leg, not a ticker.) Same test as db.js isSharesAcct.
const isShares = (r) =>
  String(r.Currency).toUpperCase() === 'SHARES' || /share|stock/i.test(String(r.Subtype || ''));

const acctId = {}, acctMeta = {};
const accounts = sheet('Accounts').filter((r) => r.Name).map((r, i) => {
  const name = String(r.Name).trim();
  const subtype = txt(r.Subtype);
  if (!subtype || !(subtype in typeBySubtype)) fail('Accounts: "' + name + '" has subtype ' + JSON.stringify(subtype) + ' with no AccountType row');
  acctId[name] = i + 1;
  acctMeta[name] = { subtype, type: typeBySubtype[subtype], currency: txt(r.Currency) || 'PHP',
                     startU: toU(r['Starting Balance']),
                     sheetNative: numOrNull(r['Current Balance']),
                     sheetPhp: numOrNull(r['Current Balance (PHP)']) };
  return {
    id: i + 1, name, currency: txt(r.Currency) || 'PHP', subtype,
    symbol: isShares(r) ? name : null,
    starting_balance_u: toU(r['Starting Balance']),
    interest_frequency: txt(r['Interest Frequency']),
    interest_rate: numOrNull(r['Interest Rate']),
    credit_limit_u: uOrNull(r['Credit Limit']),
    notes: txt(r.Notes),
    color: txt(r.Color)
  };
});
insert('accounts', ['id', 'name', 'currency', 'subtype', 'symbol', 'starting_balance_u',
                    'interest_frequency', 'interest_rate', 'credit_limit_u', 'notes', 'color'], accounts);

// ── categories ───────────────────────────────────────────────────────────────
const catId = {}, catType = {};
const categories = sheet('Categories').filter((r) => r.Category).map((r, i) => {
  const name = String(r.Category).trim();
  const type = String(r.Type || '').trim();
  if (['Income', 'Expense', 'Transfer'].indexOf(type) === -1)
    fail('Categories: "' + name + '" has Type ' + JSON.stringify(r.Type) + ' (must be Income/Expense/Transfer)');
  catId[name] = i + 1; catType[name] = type;
  return { id: i + 1, name, type, segment: txt(r.Segment), description: txt(r.Description) };
});
insert('categories', ['id', 'name', 'type', 'segment', 'description'], categories);

// ── transactions ─────────────────────────────────────────────────────────────
const seenId = new Set();
const transactions = [];
sheet('Transactions').forEach((r, i) => {
  const where = 'Transactions row ' + (i + 2);
  // Sheet row 2 is the ARRAYFORMULA anchor: setupMigration stamped an ID on it, nothing else.
  if (blank(r.Date) && blank(r.Category) && blank(r.Account)) return;
  const id = txt(r.ID);
  if (!id) { fail(where + ': no ID (run the v1 setupMigration before exporting)'); return; }
  if (seenId.has(id)) { fail(where + ': duplicate ID ' + id); return; }
  seenId.add(id);
  const cat = txt(r.Category), acct = txt(r.Account), to = txt(r.ToAccount);
  if (!cat || !(cat in catId)) { fail(where + ': unknown Category ' + JSON.stringify(r.Category)); return; }
  if (!acct || !(acct in acctId)) { fail(where + ': unknown Account ' + JSON.stringify(r.Account)); return; }
  if (to && !(to in acctId)) { fail(where + ': unknown ToAccount ' + JSON.stringify(r.ToAccount)); return; }
  const date = isoDate(r.Date, where);
  if (!date) { fail(where + ': no Date'); return; }
  // The shape invariant the service layer enforces on every write — check it here too,
  // or an old hand-edited row imports as something no handler would ever have accepted.
  if ((catType[cat] === 'Transfer') !== !!to)
    fail(where + ': Transfer/ToAccount mismatch (category "' + cat + '", ToAccount ' + JSON.stringify(r.ToAccount) + ')');
  transactions.push({
    id, date, period: periodKey(r.Period, where),
    category_id: catId[cat], description: txt(r.Description),
    account_id: acctId[acct], amount_u: toU(r.Amount),
    fx_rate: numOrNull(r.ExchangeRate),
    to_account_id: to ? acctId[to] : null,
    to_amount_u: to ? toU(blank(r.ToAmount) ? r.Amount : r.ToAmount) : null
  });
});
insert('transactions', ['id', 'date', 'period', 'category_id', 'description', 'account_id',
                        'amount_u', 'fx_rate', 'to_account_id', 'to_amount_u'], transactions);

// ── budgets ──────────────────────────────────────────────────────────────────
const budgets = sheet('Budgets').filter((r) => r.Segment).map((r, i) => ({
  id: i + 1, segment: String(r.Segment).trim(),
  period: /quarter/i.test(String(r.Period)) ? 'Quarterly' : 'Monthly',
  target_type: /^(percent|%)/i.test(String(r['Target Type'] || '')) ? 'Percent' : 'Amount',
  target: num(r.Target), currency: txt(r.Currency), notes: txt(r.Notes)
}));
insert('budgets', ['id', 'segment', 'period', 'target_type', 'target', 'currency', 'notes'], budgets);

// ── recurring ────────────────────────────────────────────────────────────────
const recurring = sheet('Recurring').filter((r) => r.Description).map((r, i) => ({
  id: i + 1, description: String(r.Description).trim(), currency: txt(r.Currency),
  amount_u: uOrNull(r.Amount), fee_u: uOrNull(r['Transaction Fee']),
  months_left: blank(r['Months Left']) ? null : Math.round(num(r['Months Left'])),
  grp: txt(r.Group)
}));
insert('recurring', ['id', 'description', 'currency', 'amount_u', 'fee_u', 'months_left', 'grp'], recurring);

// ── ledger ───────────────────────────────────────────────────────────────────
// A row that references a transaction derives everything from it (the view's LEFT
// JOIN), so its literals stay NULL. A legacy row that never got linked keeps the
// figures the sheet held, which is the only place they exist.
const ledger = sheet('Ledger').map((r, i) => {
  const txId = txt(r['Transaction ID']);
  const linked = txId && seenId.has(txId);
  if (txId && !linked) fail('Ledger row ' + (i + 2) + ': Transaction ID ' + txId + ' matches no transaction (it will render as deleted)');
  return {
    id: i + 1, tx_id: txId,
    bsp_rate: numOrNull(r['BSP Reference Rate']),
    filed: txt(r['Filed?']),
    date_received: linked ? null : isoDate(r['Date Received'], 'Ledger row ' + (i + 2)),
    wise_amount_u: linked ? null : uOrNull(r['Wise Amount'])
  };
}).filter((r) => r.tx_id || r.bsp_rate !== null || r.filed || r.date_received || r.wise_amount_u !== null);
insert('ledger', ['id', 'tx_id', 'bsp_rate', 'filed', 'date_received', 'wise_amount_u'], ledger);

say('');
say("UPDATE meta SET value = '1' WHERE key = 'data_version';");

// ── reconciliation (stderr) ──────────────────────────────────────────────────
// The port of acct_computeDeltas_, run here so the numbers are checked BEFORE the
// database exists rather than after. Liability accounts track an amount OWED, so their
// deltas invert: a charge raises the balance.
const net = {};
const bump = (name, v) => {
  if (!name) return;
  net[name] = (net[name] || 0) + (acctMeta[name].type === 'Liability' ? -v : v);
};
sheet('Transactions').forEach((r) => {
  const acct = txt(r.Account), to = txt(r.ToAccount), cat = txt(r.Category);
  if (!acct || !(acct in acctMeta) || !(cat in catType)) return;
  const amt = num(r.Amount), toAmt = blank(r.ToAmount) ? amt : num(r.ToAmount);
  if (catType[cat] === 'Transfer') { bump(acct, -amt); if (to && to in acctMeta) bump(to, toAmt); }
  else if (catType[cat] === 'Expense') bump(acct, -amt);
  else bump(acct, amt);
});

const report = [];
let mismatches = 0;
Object.keys(acctMeta).forEach((name) => {
  const m = acctMeta[name];
  const computed = m.startU / M + (net[name] || 0);
  const sheetVal = m.sheetNative;
  const delta = sheetVal === null ? null : Math.round((computed - sheetVal) * 100) / 100;
  if (delta !== null && Math.abs(delta) >= 0.005) mismatches++;
  report.push([name, m.currency, computed.toFixed(4), sheetVal === null ? '—' : Number(sheetVal).toFixed(4),
               delta === null ? 'no sheet value' : (Math.abs(delta) < 0.005 ? 'ok' : 'MISMATCH ' + delta)]);
});

const err = (s) => process.stderr.write(s + '\n');
err('');
err('── counts ─────────────────────────────────────────────');
err('  account_types ' + accountTypes.length + '   accounts ' + accounts.length +
    '   categories ' + categories.length);
err('  transactions  ' + transactions.length + '   budgets ' + budgets.length +
    '   recurring ' + recurring.length + '   ledger ' + ledger.length);
err('  accounts with an IBKR symbol: ' +
    (accounts.filter((a) => a.symbol).map((a) => a.name + '=' + a.symbol).join(', ') || '(none)'));
err('');
err('── native balance reconciliation (computed vs sheet) ───');
const w = Math.max(...report.map((r) => r[0].length), 4);
report.forEach((r) => err('  ' + r[0].padEnd(w) + '  ' + r[1].padEnd(6) + '  ' +
  r[2].padStart(14) + '  ' + r[3].padStart(14) + '  ' + r[4]));
err('');
if (problems.length) {
  err('── ' + problems.length + ' PROBLEM(S) ───────────────────────────────');
  problems.forEach((p) => err('  ! ' + p));
  err('');
}
if (mismatches) err('!! ' + mismatches + ' account(s) do not reconcile — do NOT import this seed.');
else err('All accounts reconcile to the centavo.');

process.stdout.write(out.join('\n') + '\n');
process.exit(problems.length || mismatches ? 1 : 0);
